# Generated by Django 3.0.9 on 2020-08-13 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_financial_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_email',
            new_name='customer_email',
        ),
    ]
