# Generated by Django 3.1 on 2020-08-21 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_lineitem_purchase_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchOrderUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('orders', wagtail.core.fields.StreamField([('upload', wagtail.core.blocks.StreamBlock([('table', wagtail.contrib.table_block.blocks.TableBlock(table_options={'autoColumnSize': False, 'colHeaders': False, 'editor': 'text', 'height': 216, 'language': 'en', 'minSpareRows': 0, 'renderer': 'text', 'rowHeaders': True, 'startCols': 4, 'startRows': 6, 'stretchH': 'all'}))]))])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders_batchorderupload', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orders_batchorderupload', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Order Upload',
                'verbose_name_plural': 'Batch Orders Upload',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
