# Generated by Django 3.1 on 2020-08-21 08:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200821_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchorderupload',
            name='order',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='orders.order'),
        ),
        migrations.AddField(
            model_name='batchorderupload',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
