# Generated by Django 3.1 on 2020-09-03 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_lineitem_metadata'),
        ('shipping', '0003_auto_20200903_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='orders.order'),
        ),
    ]
