# Generated by Django 3.1 on 2020-08-21 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='The image which shows in the hero header of the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
