# Generated by Django 3.1 on 2020-08-22 10:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200821_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('single_column', wagtail.core.blocks.StructBlock([('column', wagtail.core.blocks.StreamBlock([], min_num=1))])), ('tow_columns', wagtail.core.blocks.StructBlock([('left', wagtail.core.blocks.StreamBlock([('simple_card', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('heading', wagtail.core.blocks.CharBlock(help_text='The title of the card which appears under the image.', max_length=255, min_length=10)), ('paragraph', wagtail.core.blocks.TextBlock(help_text='The paragraph text which appears in the card.', max_length=500, min_length=10))])), ('detail_card', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('heading', wagtail.core.blocks.CharBlock(help_text='The title of the card which appears under the image.', max_length=255, min_length=10)), ('paragraph', wagtail.core.blocks.TextBlock(help_text='The paragraph text which appears in the card.', max_length=500, min_length=10))])), ('icon_bullets', wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.CharBlock())]))], min_num=1)), ('right', wagtail.core.blocks.StreamBlock([('simple_card', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('heading', wagtail.core.blocks.CharBlock(help_text='The title of the card which appears under the image.', max_length=255, min_length=10)), ('paragraph', wagtail.core.blocks.TextBlock(help_text='The paragraph text which appears in the card.', max_length=500, min_length=10))])), ('detail_card', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('heading', wagtail.core.blocks.CharBlock(help_text='The title of the card which appears under the image.', max_length=255, min_length=10)), ('paragraph', wagtail.core.blocks.TextBlock(help_text='The paragraph text which appears in the card.', max_length=500, min_length=10))])), ('icon_bullets', wagtail.core.blocks.StructBlock([('icon', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.CharBlock())]))], min_num=1))]))], blank=True),
        ),
    ]
