# Generated by Django 3.1 on 2020-08-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200813_0326'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='sales_order_item',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='sales_order_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_item', to='orders.lineitem'),
        ),
    ]
