# Generated by Django 3.1 on 2020-08-19 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20200819_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='sales_order_items',
        ),
    ]
