# Generated by Django 3.1 on 2020-08-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_remove_purchaseorderitem_sales_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='sales_order',
        ),
    ]
