# Generated by Django 3.1 on 2020-09-02 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariant_metadata'),
        ('purchases', '0004_remove_purchaseorder_sales_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='products.productvariant'),
        ),
    ]
