# Generated by Django 3.1 on 2020-08-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblink_channel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblinkorder',
            name='shipping_method',
            field=models.CharField(max_length=255, null=True, verbose_name='Shipping Method'),
        ),
    ]
