# Generated by Django 3.1 on 2020-08-18 03:40

from django.db import migrations
import django_measurement.models
import measurement.measures.mass


class Migration(migrations.Migration):

    dependencies = [
        ('weblink_channel', '0002_weblinkorder_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblinkorder',
            name='weight',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True),
        ),
    ]
