# Generated by Django 3.1 on 2020-08-18 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblink_channel', '0004_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weblinkorderitem',
            old_name='prodivded_price',
            new_name='provided_price',
        ),
        migrations.RenameField(
            model_name='weblinkorderitem',
            old_name='prodivded_price_currency',
            new_name='provided_price_currency',
        ),
    ]
