# Generated by Django 3.1 on 2020-08-18 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblink_channel', '0005_auto_20200818_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='puchase_order',
            new_name='purchase_order',
        ),
    ]
