# Generated by Django 3.1 on 2020-08-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblink_channel', '0011_purchaseorder_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='recieved',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('recieved', 'Recieved'), ('partial', 'Partially Recieved')], default='draft', max_length=100, verbose_name='Stauts'),
        ),
    ]
