# Generated by Django 3.1 on 2020-08-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblink_channel', '0012_auto_20200818_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('recieved', 'Recieved'), ('partial', 'Partially Recieved')], default='draft', max_length=100, verbose_name='Status'),
        ),
    ]
