# Generated by Django 3.1 on 2020-08-19 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200813_0203'),
        ('weblink_channel', '0014_weblinkorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='weblinkorderitem',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weblink_order_item', to='products.productvariant'),
        ),
    ]
