# Generated by Django 3.1 on 2020-08-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblink_channel', '0015_weblinkorderitem_variant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseorderitem',
            options={'verbose_name': 'Purchase Order Item', 'verbose_name_plural': 'Purchase Order Items'},
        ),
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='recieved',
            new_name='received',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('received', 'Received'), ('partial', 'Partially Recieved')], default='draft', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('received', 'Received'), ('partial', 'Partially Recieved')], default='draft', max_length=100, verbose_name='Stauts'),
        ),
        migrations.AlterField(
            model_name='weblinkorder',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('init', 'Purchase Order Made'), ('submitted', 'Submitted Purchase Order'), ('stock-received', 'Stock Received'), ('sent', 'Stock Sent to Customer'), ('cancelled', 'Order Cancelled')], default='new', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='weblinkorderitem',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('init', 'Puchase Order Made'), ('submitted', 'Submitted Purchase Order'), ('stock-received', 'Stock Received'), ('sent', 'Stock Sent to Customer'), ('cancelled', 'Order Cancelled')], default='new', max_length=100, verbose_name='Status'),
        ),
    ]
