# Generated by Django 3.1 on 2020-08-19 09:07

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200813_0326'),
        ('products', '0004_auto_20200813_0203'),
        ('weblink_channel', '0018_auto_20200819_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='sales_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weblink_purchase_orders', to='weblink_channel.weblinkorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weblink_purchase_orders', to='products.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='customer_order_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weblink_purchase_order_item', to='orders.lineitem'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='weblink_items', to='weblink_channel.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='sales_order_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='web_purchase_order_item', to='weblink_channel.weblinkorderitem'),
        ),
    ]
