# Generated by Django 3.0.9 on 2020-08-12 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifysynclog',
            name='status_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Status Code'),
        ),
    ]
