# Generated by Django 3.1 on 2020-08-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0002_auto_20200812_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifysynclog',
            name='response_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
