# Generated by Django 3.1 on 2020-09-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify_sync', '0004_errorsynclog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopifysynclog',
            old_name='response_data',
            new_name='data',
        ),
        migrations.AddField(
            model_name='shopifysynclog',
            name='object_type',
            field=models.CharField(blank=True, choices=[('product', 'Product'), ('order', 'Order')], max_length=100, verbose_name='Object Type'),
        ),
    ]
