# Generated by Django 3.0.9 on 2020-08-10 12:52

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200810_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
