# Generated by Django 3.0.9 on 2020-08-13 02:03

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200810_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='cost_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
