# Generated by Django 3.1 on 2020-08-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200813_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
