# Generated by Django 3.1 on 2020-09-07 03:48

from django.db import migrations
import django_measurement.models
import measurement.measures.distance


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200907_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='depth',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='height',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='width',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.distance.Distance, null=True),
        ),
    ]
