# Generated by Django 3.1 on 2020-09-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200907_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
