name: Build The Images

on:
  push:
    branches:
      - master

env:
  REPO: "mrb101"
  IMAGE: "assistant"
  REGISTRY_HOSTNAME: docker.pkg.github.com
  GITHUB_SHA: ${{ github.sha }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      # Build the Docker image
      - name: Build Django
        run: |
          docker build \
            --tag "$REGISTRY_HOSTNAME"/"$REPO"/"$IMAGE"/django:"$GITHUB_SHA" \
            --file compose/production/django/Dockerfile \
            "."

      - name: Build AWS
        run: |
          docker build \
            --tag "$REGISTRY_HOSTNAME"/"$REPO"/"$IMAGE"/aws:latest \
            --file compose/production/aws/Dockerfile \
            "."

      - name: Build Traefik
        run: |
          docker build \
            --tag "$REGISTRY_HOSTNAME"/"$REPO"/"$IMAGE"/traefik:latest \
            --file compose/production/traefik/Dockerfile \
            "."

      # Push the Docker image to Google Container Registry
      - name: Publish Images
        run: |
          echo $GH_TOKEN | docker login docker.pkg.github.com -u mrb101 --password-stdin
          docker push $REGISTRY_HOSTNAME/$REPO/$IMAGE/django:$GITHUB_SHA
          docker push $REGISTRY_HOSTNAME/$REPO/$IMAGE/aws:latest
          docker push $REGISTRY_HOSTNAME/$REPO/$IMAGE/traefik:latest
